CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT);
CREATE TABLE IF NOT EXISTS "twitch_users" ("id" TEXT PRIMARY KEY, "login" TEXT NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "display" TEXT);
CREATE TABLE IF NOT EXISTS "teej_coins" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_user_id" TEXT CONSTRAINT "teej_coins_twitch_user_id_fkey" REFERENCES "twitch_users"("id"), "amount" INTEGER DEFAULT 0 NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE UNIQUE INDEX "teej_coins_twitch_user_id_index" ON "teej_coins" ("twitch_user_id");
CREATE TABLE IF NOT EXISTS "channel_rewards" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_reward_id" TEXT NOT NULL, "twitch_reward_cost" INTEGER NOT NULL, "title" TEXT NOT NULL, "prompt" TEXT NOT NULL, "is_user_input_required" INTEGER DEFAULT false NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "max_per_stream" INTEGER NULL, "max_per_user_per_stream" INTEGER NULL, "global_cooldown_seconds" INTEGER NULL, "key" TEXT NULL);
CREATE TABLE IF NOT EXISTS "chat_messages" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_user_id" TEXT CONSTRAINT "chat_messages_twitch_user_id_fkey" REFERENCES "twitch_users"("id"), "text" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "coin_ledger" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_user_id" TEXT CONSTRAINT "coin_ledger_twitch_user_id_fkey" REFERENCES "twitch_users"("id"), "amount" INTEGER NOT NULL, "reason" TEXT NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "twitch_accounts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" TEXT NOT NULL COLLATE NOCASE, "hashed_password" TEXT NOT NULL, "confirmed_at" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "twitch_accounts_email_index" ON "twitch_accounts" ("email");
CREATE TABLE IF NOT EXISTS "twitch_accounts_tokens" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_id" INTEGER NOT NULL CONSTRAINT "twitch_accounts_tokens_twitch_id_fkey" REFERENCES "twitch_accounts"("id") ON DELETE CASCADE, "token" BLOB NOT NULL, "context" TEXT NOT NULL, "sent_to" TEXT, "inserted_at" TEXT NOT NULL);
CREATE INDEX "twitch_accounts_tokens_twitch_id_index" ON "twitch_accounts_tokens" ("twitch_id");
CREATE UNIQUE INDEX "twitch_accounts_tokens_context_token_index" ON "twitch_accounts_tokens" ("context", "token");
CREATE UNIQUE INDEX "channel_rewards_twitch_reward_id_index" ON "channel_rewards" ("twitch_reward_id");
CREATE TABLE IF NOT EXISTS "redemption_ledger" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_user_id" TEXT CONSTRAINT "redemption_ledger_twitch_user_id_fkey" REFERENCES "twitch_users"("id"), "twitch_reward_id" TEXT NOT NULL, "twitch_reward_title" TEXT NOT NULL, "twitch_cost" INTEGER NOT NULL, "twitch_prompt" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "themesongs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_user_id" TEXT CONSTRAINT "themesongs_twitch_user_id_fkey" REFERENCES "twitch_users"("id"), "name" TEXT, "path" TEXT, "length_ms" INTEGER);
CREATE UNIQUE INDEX "themesongs_twitch_user_id_index" ON "themesongs" ("twitch_user_id");
CREATE TABLE IF NOT EXISTS "effects" ("id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "prompt" TEXT NOT NULL, "cost" INTEGER, "is_user_input_required" INTEGER DEFAULT false NOT NULL, "enabled_on" TEXT NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "cooldown" INTEGER NULL, "max_per_stream" INTEGER NULL, "max_per_user_per_stream" INTEGER NULL);
CREATE TABLE IF NOT EXISTS "oban_jobs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "state" TEXT DEFAULT 'available' NOT NULL, "queue" TEXT DEFAULT 'default' NOT NULL, "worker" TEXT NOT NULL, "args" JSON DEFAULT ('{}') NOT NULL, "meta" JSON DEFAULT ('{}') NOT NULL, "tags" JSON DEFAULT ('[]') NOT NULL, "errors" JSON DEFAULT ('[]') NOT NULL, "attempt" INTEGER DEFAULT 0 NOT NULL, "max_attempts" INTEGER DEFAULT 20 NOT NULL, "priority" INTEGER DEFAULT 0 NOT NULL, "inserted_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL, "scheduled_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL, "attempted_at" TEXT, "attempted_by" JSON DEFAULT ('[]') NOT NULL, "cancelled_at" TEXT, "completed_at" TEXT, "discarded_at" TEXT);
CREATE INDEX "oban_jobs_state_queue_priority_scheduled_at_id_index" ON "oban_jobs" ("state", "queue", "priority", "scheduled_at", "id");
CREATE TABLE IF NOT EXISTS "effect_status" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "status" TEXT NOT NULL, "effect_id" INTEGER NOT NULL CONSTRAINT "effect_status_effect_id_fkey" REFERENCES "effects"("id"), "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "effect_status_effect_id_index" ON "effect_status" ("effect_id");
CREATE TABLE IF NOT EXISTS "status_ledger" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "twitch_user_id" TEXT NOT NULL CONSTRAINT "status_ledger_twitch_user_id_fkey" REFERENCES "twitch_users"("id"), "effect_id" TEXT NOT NULL CONSTRAINT "status_ledger_effect_id_fkey" REFERENCES "effects"("id"), "prompt" TEXT NULL, "cost" INTEGER NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "effect_ledger" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "prompt" TEXT, "cost" INTEGER, "reason" TEXT, "effect_id" INTEGER CONSTRAINT "effect_ledger_effect_id_fkey" REFERENCES "effects"("id"), "twitch_user_id" INTEGER CONSTRAINT "effect_ledger_twitch_user_id_fkey" REFERENCES "twitch_users"("id"), "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "effect_ledger_effect_id_index" ON "effect_ledger" ("effect_id");
CREATE INDEX "effect_ledger_twitch_user_id_index" ON "effect_ledger" ("twitch_user_id");
INSERT INTO schema_migrations VALUES(20240325144111,'2024-03-28T14:02:30');
INSERT INTO schema_migrations VALUES(20240325152535,'2024-03-28T14:02:30');
INSERT INTO schema_migrations VALUES(20240326152915,'2024-04-01T18:45:33');
INSERT INTO schema_migrations VALUES(20240401173357,'2024-04-01T18:45:33');
INSERT INTO schema_migrations VALUES(20240402161729,'2024-04-02T16:22:02');
INSERT INTO schema_migrations VALUES(20240402172607,'2024-04-02T17:46:32');
INSERT INTO schema_migrations VALUES(20240403141915,'2024-04-03T14:20:27');
INSERT INTO schema_migrations VALUES(20240403161028,'2024-04-03T16:18:11');
INSERT INTO schema_migrations VALUES(20240403181220,'2024-04-03T18:43:40');
INSERT INTO schema_migrations VALUES(20240409203043,'2024-04-09T20:33:59');
INSERT INTO schema_migrations VALUES(20240410184533,'2024-04-10T18:48:37');
INSERT INTO schema_migrations VALUES(20240410190931,'2024-04-10T19:09:48');
INSERT INTO schema_migrations VALUES(20240410192530,'2024-04-10T20:07:08');
INSERT INTO schema_migrations VALUES(20240410195418,'2024-04-10T20:07:09');
INSERT INTO schema_migrations VALUES(20240411151345,'2024-04-11T15:14:16');
INSERT INTO schema_migrations VALUES(20240411155940,'2024-04-11T16:08:13');
INSERT INTO schema_migrations VALUES(20240411174727,'2024-04-11T17:47:31');
